### ISSUE TITLE
Missing Video URL

### ISSUE THREAD

**Issue by Linus12** [tumblr/jumblr#70] opened 2015-10-18 20:25 UTC
The VideoPost type is missing the definition and return of the field video_url. I have copied the source, added the minor changes required and tested the changes from within my application. I have submitted pull request for this change.

I think I did it right. But if I didn't, please let me know what I did wrong so that I can better contribute any further updates I might encounter.

**Comment by Linus12** [comment] 2015-10-19 09:10
Ok, I guess I did the pull request wrong before, but now I think I added it correctly.

**Comment by KevinTCoughlin** [comment] 2015-10-19 14:13
Dupe of https://github.com/tumblr/jumblr/pull/71

**Closed by KevinTCoughlin** 2015-10-19 14:13 UTC
